apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
    - name: container1
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: container2
      image: busybox:latest
      command: ["sleep", "3600"]
